---
title: "Variations in Peterhof strains"
author: "drozdovapb"
date: "12/15/2014"
output: html_document
---

##File input

```{r}
setwd("/media/drozdovapb/big/Peterhof_strains_seq/12-06-snpeff/") #change it to ur path
fifteenV <- read.csv("./15V_coding/15V-snpEff_genes.txt", head=T, sep="\t", skip = 1, row.names=1)
twentyfive <- read.csv( "./25-25-coding/25-25-snpEff_genes.txt", head=T, sep="\t", skip = 1, row.names=1)
oneB <- read.csv("./1B_coding/1B-snpEff_genes.txt", head=T, sep="\t", skip = 1, row.names=1)
seventyfour <- read.csv("./74_coding/snpEff_genes.txt", head=T, sep="\t", skip = 1, row.names=1)

setwd("/media/drozdovapb/big/Peterhof_strains_seq/12-15-SNPs_R/") #change it to ur path
```

!!! Corrected IMP2' to IMP2 in the last two files __manually__

##15V-P4: how are Peterhof strains different?

###Stop codons
```{r}
names(fifteenV)[24:35] <- sapply(names(fifteenV)[24:35], substr, 8, 1000)
fifteenV[fifteenV$stop_gained.>0, ][c(1,2,32)]
fifteenV[fifteenV$stop_lost.>0,][c(1,2,33)]
```

##Most variable genes

```{r}
x <- table(fifteenV$Bases.affected..GENE.); x

hcum <- h <- hist(fifteenV$Bases.affected..GENE., breaks=50, col='blue', plot=FALSE)
hcum$counts <- cumsum(hcum$counts)
plot(hcum, main="")
plot(h, add=T, col="grey")

d <- density(x)
#lines(x = d$x, y = d$y * length(x) * diff(h$breaks)[1], lwd = 2)
#lines(x = d$x, y = cumsum(d$y)/max(cumsum(d$y)) * length(x), lwd = 2)


subsetFift <- fifteenV[order(fifteenV$Bases.affected..GENE., decreasing = T),][c(1,2,6)]
subsetFift[subsetFift$Bases.affected..GENE. >9,]
```

##The biggest number of missense mutations

```{r}
hist(fifteenV$missense_variant., breaks=50, col='gray')

missenseFift <- fifteenV[order(fifteenV$missense_variant., decreasing = T),][c(1,2,26)]

missenseFift[missenseFift$missense_variant.>5,]
write.table(missenseFift[missenseFift$missense_variant.>5,], 'miss.txt')

```



#twentyfive

```{r}
names(twentyfive)[24:35] <- sapply(names(twentyfive)[24:35], substr, 8, 1000)
twentyfive[twentyfive$stop_gained.>0, ][c(1,2,32)]


```

#seventyfour
```{r}
#names(seventyfour)[24:35] <- sapply(names(seventyfour)[24:35], substr, 8, 1000)
table(seventyfour$Count..stop_gained.)
seventyfour[seventyfour$Count..stop_gained.>0, ][c(1,2,28)]
seventyfour[seventyfour$Count..stop_lost.>0,][c(1,2,29)]
```



Does our analysis differ from Fitzpatrick et al., 2011?

```{r}
stops_74_our <- row.names(seventyfour[seventyfour$Count..stop_gained.>0,])
stops_74_fitz <- c("YAL056W", "YAR015W", "YAR028W", "YAR031W", 
                   "YBL037W", "YDR007W", "YDR147W", 
                   "YFR057W", "YGR159C", "YGR249W", "YGR281W", "YGR283W", 
                   "YHL003C", "YHR143W", "YIR028W", "YKL062W", "YKR056W", "YLR313C")

intersect(stops_74_our, stops_74_fitz)

setdiff(stops_74_our, stops_74_fitz)
setdiff(stops_74_fitz, stops_74_our)
```


Closer look at 15V

```{r}
fifteenV$freq.miss <- fifteenV$missense_variant./fifteenV$Length..GENE. *100
hist(fifteenV$freq.miss, col='blue', breaks=100, xlab = 'percent changes')

freqMissenseFift <- fifteenV[order(fifteenV$freq.miss, decreasing = T),][c(1,2,26,36)]

head(freqMissenseFift)

freqMissenseFift$GeneName <- as.character(freqMissenseFift$GeneName)
freqMissenseFift$ORF <- row.names(freqMissenseFift)
missenseRealGenes <- subset(freqMissenseFift, freqMissenseFift$GeneName != freqMissenseFift$ORF)

head(missenseRealGenes, n = 100)
```